[build]
  base = "/Frontend"
  publish = "Frontend/dist"
  command = "cd Frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


  

