services:
  - type: web
    name: ayushai-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: MONGODB_URI
        fromEnvVar: MONGODB_URI
      - key: JWT_SECRET
        fromEnvVar: JWT_SECRET
    healthCheckPath: /health
    allowedDomains:
      - ayushai-backend.onrender.com
    env: node
    buildCommand: npm install
    startCommand: npm start
